version: "3.3"
services:

  # RabbitMQ that connects the backend to the frontend
  queue:
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
      - "5672"
    networks:
      - rakan
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  distribution_database:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - rakan
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  # Backend
  # Frontend
  # Bladecaller
    

networks:
  rakan:

volumes:
  db-data: